require('./fetchSimulator');
const { getGitHubUserInfos } = require('../src/github');

const expected = {
  name: 'Hugo Ferreira',
  company: 'Trybe',
  twitter: 'hugonardo',
  bio: 'Teste',
  location: 'Brazil',
};

describe('A fun√ß√£o getGitHubUserInfos', () => {
  describe('quando a fun√ß√£o fetch √© resolvida', () => {

    it('os dados devem ser mapeados corretamente para um novo formato', async () => {
      expect.assertions(1);

      // const result = await getGitHubUserInfos("hugonardo");
      // expect(result).toEqual(expected);

      // Assim tamb√©m funciona!! üòä
      await expect(getGitHubUserInfos("hugonardo"))
        .resolves.toEqual(expected);
    });

    it('fun√ß√£o fetch deve ter sido chamada', async () => {
      expect.assertions(1);
      await getGitHubUserInfos("hugonardo");
      expect(fetch).toHaveBeenCalled(); // <- Isto √© importante
    });

    it('a fun√ß√£o `fetch` deve ter recebido o endpoint correto', async () => {
      expect.assertions(1);
      await getGitHubUserInfos("hugonardo");
      const user = 'hugonardo';
      const url = `https://api.github.com/users/${user}`;
      expect(fetch).toHaveBeenCalledWith(url); // <- Isto √© importante
    });
  });

  describe('quando a fun√ß√£o fetch √© rejeitada', () => {
    it('deve retornar um erro \'Usu√°rio inv√°lido\'', async () => {
      expect.assertions(1);

      // try {
      //   await getGitHubUserInfos('usuario-inexistente');
      // } catch (error) {
      //   expect(error).toEqual(new Error('Usu√°rio inv√°lido'));
      // }

      // Assim tamb√©m funciona!! üòä
      await expect(getGitHubUserInfos('usuario-inexistente'))
        .rejects.toEqual(new Error('Usu√°rio inv√°lido'))
    });
  });
});
